### ISSUE TITLE
Backward scrolling sometimes snaps twice

### ISSUE THREAD

**Issue by ghost** [TakuSemba/MultiSnapRecyclerView#13]
I have a horizontal MultiSnapRV, my XML code:
```
<com.takusemba.multisnaprecyclerview.MultiSnapRecyclerView
        android:id="@+id/rv_weeks"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        app:msrv_gravity="start"
        app:msrv_snap_count="7" />
```

When I scroll it forward, it works amazing and smooth. But if I scroll backward, sometimes it scrolls 14 positions, not 7. Is it bug or I missed something?

**Comment by TakuSemba** [comment]
there is a bug like that at some old versions.
what version are you using? I thought that was resolved at the latest version of 1.3.3

**Comment by ghost** [comment]
Im using the last 1.3.3 version and this bug is still here..

**Comment by TakuSemba** [comment]
Ok, I'll check into it.

**Comment by TakuSemba** [comment]
Is it possible to send me a gif or video of that happening?

**Comment by ghost** [comment]
![ezgif-2-d83357622f](https://user-images.githubusercontent.com/22007237/40913858-a9d4b45e-67fe-11e8-91e9-e85852023b9f.gif)

Here we go

**Comment by foxwoosh** [comment]
Is there any progress? Or maybe I should just do a pull request.. I need this fix :(

**Comment by TakuSemba** [comment]
sorry, I could not make time for this, a pull request is welcome :)

**Comment by TakuSemba** [comment]
I tried your case but did not happen.

Can you try the new version of 2.0.0?
If it still happens, it would be really appreciated if you could add your case in the sample app module so that I can look into it.

**Comment by TakuSemba** [comment]
Please reopen this if this still happens on v2.x.x. Thank you! :)
